--CREATE DATABASE cloud_render_api;

CREATE TABLE IF NOT EXISTS order_statuses(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL
);

CREATE TABLE IF NOT EXISTS orders(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fileName text NOT NULL,
    creation_date date NOT NULL,
    user_id int NOT NULL,
    status_id int NOT NULL,
    download_link text,
    is_deleted bool NOT NULL,
    FOREIGN KEY (status_id) REFERENCES order_statuses (id)
);

CREATE TABLE IF NOT EXISTS payment_types(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS payments(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id int NOT NULL,
    type_id int NOT NULL,
    date timestamp NOT NULL,
    FOREIGN KEY (type_id) REFERENCES payment_types (id)
);

CREATE TABLE IF NOT EXISTS subscription_types(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL
);

CREATE TABLE IF NOT EXISTS subscriptions(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id int NOT NULL,
    type_id int NOT NULL,
    sub_expire_date timestamp NOT NULL,
    FOREIGN KEY (type_id) REFERENCES subscription_types (id)
);

INSERT INTO payment_types (name) VALUES ('sub-premium-month');
INSERT INTO subscription_types (name) VALUES ('premium');
