CREATE DATABASE cloud_render;

CREATE TABLE IF NOT EXISTS users(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login text UNIQUE NOT NULL,
    email text UNIQUE NOT NULL,
    password text NOT NULL,
    sub_expire_date timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS orders(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fileName text NOT NULL,
    user_id int NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS payment_types(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS payments(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date timestamp NOT NULL,
    type_id int NOT NULL,
    user_id int NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id),
    FOREIGN KEY (type_id) REFERENCES payment_types (id)
);
