env: "local"
storage_path: "user=postgres password=Sever312 dbname=render-backend-api sslmode=disable"
http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 30s
envs:
  storage: "STORAGE_PATH"
  jwt_secret: "JWT_SECRET_KEY"
